package lv.cebbys.mcmods.celib.dataloader.factories;

import com.google.gson.JsonObject;
import lv.cebbys.mcmods.celib.dataloader.factories.old.CelibResourceFactory;
import lv.cebbys.mcmods.celib.dataloader.resources.JsonObjectResource;

public class PackMcmetaFactory implements CelibResourceFactory<JsonObjectResource> {

    private int packFormat;
    private String description;

    public PackMcmetaFactory() {
        this.packFormat = 7;
        this.description = "Resource Pack generated by Celib Data Loader";
    }

    public void packFormat(int f) {
        this.packFormat = f;
    }

    public void description(String d) {
        this.description = d;
    }

    @Override
    public JsonObjectResource createResource() {
        final JsonObject json = new JsonObject();
        final JsonObject pack = new JsonObject();
        pack.addProperty("pack_format", this.packFormat);
        pack.addProperty("description", this.description);
        json.add("pack", pack);
        return () -> json;
    }
}
